# Makefile for flashUtilities

flashUtilities += removeNullChar.o \
                  current_date_time.o \
		  concatStringWithInt.o \
                  ut_getFreeFileUnit.o \
                  ut_constRealZeroFn1.o \
                  ut_quadraticRoots.o \
                  ut_cubicRoots.o \
                  ut_quarticRoots.o
