#	Makefile for treecol module
TreeCol = TreeCol_init.o TreeCol_finalize.o \
          TreeCol_interface.o \
          TreeCol_bhAccBotNode.o \
          TreeCol_bhAccNode.o \
          TreeCol_bhBotNodeContrib.o \
          TreeCol_bhFillBotNode.o \
          TreeCol_bhFinalizeBlock.o \
          TreeCol_bhGetNodeStruct.o \
          TreeCol_bhInitFieldVar.o \
          TreeCol_bhMAC.o \
          TreeCol_bhNodeContrib.o \
          TreeCol_bhNormalizeNode.o \
          TreeCol_bhPartErr.o \
          TreeCol_bhPostprocNode.o \
          TreeCol_bhSelfContrib.o \
          TreeCol_bhStartBlock.o


