# Makefile for flashUtilities

flashUtilities += ut_biCubicCoefficients.o         \
                  ut_cubicInterpolationInterface.o \
		  ut_monoCubicCoefficients.o       \
		  ut_triCubicCoefficients.o

