#	Makefile for gravity module
Gravity += Gravity_init.o Gravity_finalize.o \
          Gravity_bhFillBotNode.o Gravity_bhAccBotNode.o \
          Gravity_bhNormalizeNode.o Gravity_bhAccNode.o \
          Gravity_bhNodeContrib.o Gravity_bhBotNodeContrib.o \
          Gravity_bhPostprocNode.o Gravity_bhPartErr.o\
          Gravity_bhMAC.o Gravity_bhSelfContrib.o \
          Gravity_bhGetNodeStruct.o \
          Gravity_bhInitFieldVar.o Gravity_computeDt.o \
          Gravity_accelListOfBlocks.o \
	      Gravity_accelAtCoords.o \
          Gravity_potentialListOfBlocks.o \
          Gravity_bhStartBlock.o \
          Gravity_bhFinalizeBlock.o \
          grv_bhInterface.o Gravity_data.o \
          Gravity_bhEwald.o Gravity_bhGenEwaldField.o \
          Gravity_bhGenEwaldFieldLevel.o \
          grv_elintF.o grv_intCoef1P2I.o

