!!****f* source/source_terms/Cool/CoolMain/Cool_init
!!
!! NAME
!!  
!!  Cool_init
!!
!!
!! SYNOPSIS
!! 
!!  call Cool_init(integer(IN) :: myPE)
!!  
!! DESCRIPTION
!!
!!  Apply the radloss source term operator to a block of zones.
!!  The radiative losses rate is used to update the
!!  internal energy in the zone. The radiative losses from an 
!!  optically thin plasma are from Sarazin (1986) Rev.Mod.Phys.
!!  and from Raymond (1976).
!!  (see also Peres et al. 1982, ApJ 252, 791)
!!
!!  After we call radloss, call the eos to update the pressure 
!!  and temperature based on the radiative losses.
!!
!!
!!***

subroutine Cool_init (myPE)
      use Cool_data
      use RuntimeParameters_interface, ONLY : RuntimeParameters_get
      use PhysicalConstants_interface, ONLY:  PhysicalConstants_get

#include "constants.h"
#include "Flash.h"

      implicit none
      integer, intent(IN) :: myPE
      integer :: i,j
      real    :: d1,d2,d3,d4,d5,d6
      Character(LEN=40) :: Fmt



!
!==============================================================================
!
      call PhysicalConstants_get("proton mass", amu)
      call RuntimeParameters_get("tradmin", tradmin)      
      call RuntimeParameters_get("tradmax", tradmax)
      call RuntimeParameters_get("dradmin", dradmin)
      call RuntimeParameters_get("dradmax", dradmax)
      call RuntimeParameters_get("massfracH", massfracH)
      call RuntimeParameters_get("nocool", nocool)
!     Metallicity in solar
      call RuntimeParameters_get("metallicity", metallicity)
!     UV flux as in the paper
      call RuntimeParameters_get("G0", G0)

!     Initial dust fraction in solar AFTER THE DESTRUCTION PHASE!!!!
!     WARNING... THE CODE IS ASSUMING SOLAR DUST CONTENT and then
!     taking dustinit to decrease grain size will leaving the number density
!     alone.. this matters for the rad cooling...
      call RuntimeParameters_get("dustinit", dustinit)      
!     Initial dust grain size in microns
      call RuntimeParameters_get("A0", A0)
!     Initial dust grain density in g/cm^3
      call RuntimeParameters_get("graindensity", graindensity)
!     Initial dust grain mass in amu  
      mdust0 = 4.*3.1415/3.*(A0*1E-4)**3*graindensity
!     Dust destruction rate coefficient A in microns per year
      call RuntimeParameters_get("Adust", Adust)
!     Convert to cgs
      Adust = Adust/365.25/24./3600.
!     Dust destruction rate coefficient B 
      call RuntimeParameters_get("Bdust", Bdust)
!     this is the number of ionizing photons per second generated by the source
!     units of 1E50 per second
      call RuntimeParameters_get("Ngamma", Ngamma)
!     A logical parameter that turns on SelfShielding 
      call RuntimeParameters_get("selfshield",selfshield)
!     This size of a self-sheilding blob in cm 
      call RuntimeParameters_get("shieldlength",shieldlength)
!     This is the distance to the source 
      call RuntimeParameters_get("sourcedist",sourcedist)
!     Compton luminosity in units of solar 
      call RuntimeParameters_get("Comptonlum",Comptonlum)
!     Compton flux in ergs/s/cm&2
      Comptonflux = Comptonlum*3.8E33/(4*3.14159264*sourcedist**2)
!     Compton temperature in keV
      call RuntimeParameters_get("Comptontemp",Comptontemp)
      ComptontempK = Comptontemp*1.16E7/4.
!     this is the ionization rate in units of 1/sec (Ngamma*cross
!     section*1E50/4PI/dist^2)
      Gammapi = Ngamma*6.3E32/(4.*3.14159265*sourcedist**2)     

      if(myPE == MASTER_PE) then
        print *,'Comptonflux',Comptonflux,'ergs/s/cm^2'
        print *,'ComptontempK',ComptontempK,'K'      
        print *,'Gammapi',Gammapi,'Gammapi from the paper'
      endif
      open(unit=2,file="./cool.txt")
 !    the density is from 6 x 10^-2 6 x 10^4 in baryonic (H + He) number density
      do j= 1,241
        do i= 1,161
!      read in logT, then total cooling and heating then metal only part
         read(2,*) d1,d2,d3,d4,d5,d6
          hhe_cooling(j,i)=d3
          hhe_heating(j,i)=d4 
          total_cooling(j,i)=d5
          total_heating(j,i)=d6 
        end do 
      end do
      close(2)

!     If this is the master processor, write a file with the cooling
!     functions as a check
      if(myPE == MASTER_PE) then 
        !Fmt="(ES11.3,ES11.3,ES11.3,ES11.3,ES11.3,ES11.3)"
        open(unit=2,file="./cool_check.txt")
        do j= 1,241
          do i= 1,161
           d1 = i
           d1 = 10**(1.+(d1-1.)/20.)
           d2 = j
           d2 = 60.*10**(-3.+(d2-1.)/20.)
          end do
        end do
      close(2)
      endif 
      return
end subroutine Cool_init
