Cool += Cool_init.o Cool.o Cool_computeDt.o Cool_finalize.o Cool_interface.o \
	Cool_unitTest.o
#	Makefile for cooling module 

Cool += Cool_data.o Cool_block.o radloss.o


Cool_block.o    : radloss.o

