Conductivity += Conductivity_init.o Conductivity_finalize.o \
		Conductivity.o Conductivity_interface.o 
Conductivity += Conductivity_data.o Conductivity_fullState.o
Conductivity += Conductivity_data.o \
                Conductivity_fullState.o \
                cond_logLambda.o \
                cond_logLambdaII.o
