#  Makefile for QSO setup 

Simulation += Simulation_data.o Simulation_sendOutputData.o sim_ranmar.o 
Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o
Simulation_sendOutputData.o : Simulation_data.o

