        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb  5 15:03:42 2015
        MODULE MA28INT2__genmod
          INTERFACE 
            SUBROUTINE MA28INT2
            END SUBROUTINE MA28INT2
          END INTERFACE 
        END MODULE MA28INT2__genmod
