        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb  5 15:03:42 2015
        MODULE MA28INT1__genmod
          INTERFACE 
            SUBROUTINE MA28INT1
            END SUBROUTINE MA28INT1
          END INTERFACE 
        END MODULE MA28INT1__genmod
