        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb  5 15:03:42 2015
        MODULE MA28INT3__genmod
          INTERFACE 
            SUBROUTINE MA28INT3
            END SUBROUTINE MA28INT3
          END INTERFACE 
        END MODULE MA28INT3__genmod
